version: "3.0.0-alpha.26"
slug: hamh
name: Home-Assistant-Matter-Hub
description: Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
url: https://github.com/t0bst4r/home-assistant-matter-hub
arch:
  - aarch64
  - amd64
  - armv7
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
ingress: true
ingress_port: 0
init: false
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
panel_icon: mdi:bridge
panel_title: Matter bridges
schema:
  app_log_level: list(silly|debug|info|warn|error)
  disable_log_colors: bool
  mdns_network_interface: "str?"
